# Python 中 sqlite 绑定的时候出现不支持的类型错误
- Python,sqlite,不支持的类型错误

在 Python 中进行 sqlite 的操作，经常需要拼接 sql 语句。在执行 conn.execute() 方法的时候，python 会进行数据的绑定，把对应的数据绑定到 ? 上，如果绑定的数据格式不正确，会出现 probaly unsupported type 的错误，


    Traceback (most recent call last):
        File "./main.py", line 56, in <module>
        update_all_funds_to_tables()
        File "./main.py", line 52, in update_all_funds_to_tables
        update_or_insert_fund_to_index(fund,funds['display_name'][fund],funds['name'][fund],funds['start_date'][fund],funds['end_date'][fund],funds['type'][fund])
      File "./main.py", line 42, in update_or_insert_fund_to_index
    ''',(fund,display_name,name,start_date,end_date,ftype))
    sqlite3.InterfaceError: Error binding parameter 3 - probably unsupported type.

出现这种问题的时候，我们需要检查一下传递参数的数据类型。

